/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import main.InitData;
import main.ReadTxt;

/**
 *
 * @author JendersonQ
 */
public class InitParameters extends javax.swing.JFrame {

    public ReadTxt txt;
    public InitData dataInit;

    /**
     * Creates new form InitParameters
     */
    public InitParameters() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.txt = new ReadTxt();

        this.dataInit = txt.getParametersInit();
        this.setValuesInit();
    }

    private void setValuesInit() {
        this.textDurationInS.setText(Integer.toString(this.dataInit.getDurationInS()));
        this.textDeadline.setText(Integer.toString(this.dataInit.getDeadline()));
        this.textCChasis.setText(Integer.toString(this.dataInit.getMountChasisInit()));
        this.textCCarroceria.setText(Integer.toString(this.dataInit.getMountCarroceriaInit()));
        this.textCRueda.setText(Integer.toString(this.dataInit.getMountRuedaInit()));
        this.textCMotor.setText(Integer.toString(this.dataInit.getMountMotorInit()));
        this.textCAccesorio.setText(Integer.toString(this.dataInit.getMountAccesorioInit()));
        this.textEnsamblador.setText(Integer.toString(this.dataInit.getMountEnsambladorInit()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        textEnsamblador = new javax.swing.JTextField();
        textDurationInS = new javax.swing.JTextField();
        textDeadline = new javax.swing.JTextField();
        textCChasis = new javax.swing.JTextField();
        textCCarroceria = new javax.swing.JTextField();
        textCRueda = new javax.swing.JTextField();
        textCMotor = new javax.swing.JTextField();
        textCAccesorio = new javax.swing.JTextField();
        btnSaveData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipal.setText("Parametros iniciales");
        jPanel1.add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 440, 40));
        jPanel1.add(textEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 160, 30));
        jPanel1.add(textDurationInS, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, 30));
        jPanel1.add(textDeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 160, 30));
        jPanel1.add(textCChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 160, 30));
        jPanel1.add(textCCarroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 160, 30));
        jPanel1.add(textCRueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 160, 30));
        jPanel1.add(textCMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 160, 30));
        jPanel1.add(textCAccesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 30));

        btnSaveData.setText("Guardar");
        btnSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDataActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveData, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 110, 30));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ensambladores:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 130, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Duración del día en seg:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 150, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tiempo limite de entrega:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 150, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Creadores de chasis:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 130, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Creadores de Carroceria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 140, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Creadores de Rueda:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 130, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Creadores de Motor:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 130, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Creadores de Accesorios:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 140, -1));

        salir.setBackground(new java.awt.Color(255, 51, 51));
        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 0, 0));
        salir.setText("x");
        salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        salir.setBorderPainted(false);
        salir.setFocusPainted(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void btnSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDataActionPerformed

        try {
            int sumWorkers = (Integer.parseInt(this.textCChasis.getText())
                    +Integer.parseInt(this.textCCarroceria.getText())
                    +Integer.parseInt(this.textCRueda.getText())
                    +Integer.parseInt(this.textCMotor.getText())
                    +Integer.parseInt(this.textCAccesorio.getText())
                    +Integer.parseInt(this.textEnsamblador.getText()));
        
            if (sumWorkers > 10) {
                JOptionPane.showMessageDialog(null, "Excede el máximo de trabajadores", "Empleados a tope",0);
            } else {
                InitData newParameters = new InitData();
                newParameters.setDurationInS(Integer.parseInt(this.textDurationInS.getText()));
                newParameters.setDeadline(Integer.parseInt(this.textDeadline.getText()));
                newParameters.setMountChasisInit(Integer.parseInt(this.textCChasis.getText()));
                newParameters.setMountCarroceriaInit(Integer.parseInt(this.textCCarroceria.getText()));
                newParameters.setMountRuedaInit(Integer.parseInt(this.textCRueda.getText()));
                newParameters.setMountMotorInit(Integer.parseInt(this.textCMotor.getText()));
                newParameters.setMountAccesorioInit(Integer.parseInt(this.textCAccesorio.getText()));
                newParameters.setMountEnsambladorInit(Integer.parseInt(this.textEnsamblador.getText()));
                
                this.txt.updateParameters(newParameters);
                JOptionPane.showMessageDialog(null, "Actualización exitosa", "Parametros actualizados",1);
                this.setVisible(false);
            }
            
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor ingresado no es numerico", "Error tipo de dato",0);
        }


    }//GEN-LAST:event_btnSaveDataActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InitParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InitParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InitParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InitParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InitParameters().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    private javax.swing.JTextField textCAccesorio;
    private javax.swing.JTextField textCCarroceria;
    private javax.swing.JTextField textCChasis;
    private javax.swing.JTextField textCMotor;
    private javax.swing.JTextField textCRueda;
    private javax.swing.JTextField textDeadline;
    private javax.swing.JTextField textDurationInS;
    private javax.swing.JTextField textEnsamblador;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
