/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author JendersonQ
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPantalla = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        panelBugatti = new javax.swing.JPanel();
        panelTituloBugatti = new javax.swing.JPanel();
        titulo4 = new javax.swing.JLabel();
        panelEmpleadosBugatti = new javax.swing.JPanel();
        titulo5 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        titulo10 = new javax.swing.JLabel();
        titulo11 = new javax.swing.JLabel();
        titulo12 = new javax.swing.JLabel();
        titulo13 = new javax.swing.JLabel();
        titulo14 = new javax.swing.JLabel();
        titulo15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        panelAlmacenBugatti = new javax.swing.JPanel();
        titulo22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        titulo23 = new javax.swing.JLabel();
        titulo24 = new javax.swing.JLabel();
        titulo25 = new javax.swing.JLabel();
        titulo26 = new javax.swing.JLabel();
        titulo27 = new javax.swing.JLabel();
        titulo28 = new javax.swing.JLabel();
        titulo29 = new javax.swing.JLabel();
        titulo30 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        panelLamborguini = new javax.swing.JPanel();
        panelTituloLamborguini = new javax.swing.JPanel();
        titulo6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        titulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelPantalla.setBackground(new java.awt.Color(255, 255, 255));
        panelPantalla.setMinimumSize(new java.awt.Dimension(1366, 768));
        panelPantalla.setPreferredSize(new java.awt.Dimension(1366, 768));
        panelPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipal.setText("2023 © Norangel Marin y Jenderson Quintero");
        panelPantalla.add(tituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 1366, 30));

        panelBugatti.setBackground(new java.awt.Color(153, 255, 153));
        panelBugatti.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelBugatti.setPreferredSize(new java.awt.Dimension(1366, 768));
        panelBugatti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTituloBugatti.setBackground(new java.awt.Color(0, 255, 153));
        panelTituloBugatti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo4.setBackground(new java.awt.Color(0, 0, 0));
        titulo4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        titulo4.setForeground(new java.awt.Color(0, 0, 0));
        titulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo4.setText("Bugatti");
        titulo4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTituloBugatti.add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 710, 40));

        panelBugatti.add(panelTituloBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 690, 40));

        panelEmpleadosBugatti.setBackground(new java.awt.Color(0, 255, 153));
        panelEmpleadosBugatti.setForeground(new java.awt.Color(0, 0, 0));
        panelEmpleadosBugatti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo5.setBackground(new java.awt.Color(0, 0, 0));
        titulo5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo5.setForeground(new java.awt.Color(0, 0, 0));
        titulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo5.setText("Empleados");
        panelEmpleadosBugatti.add(titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 340, 20));

        titulo3.setBackground(new java.awt.Color(0, 0, 0));
        titulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo3.setForeground(new java.awt.Color(0, 0, 0));
        titulo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo3.setText("Total de empleados:");
        panelEmpleadosBugatti.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, -1));

        titulo10.setBackground(new java.awt.Color(0, 0, 0));
        titulo10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo10.setForeground(new java.awt.Color(0, 0, 0));
        titulo10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo10.setText("Creadores de Chasis:");
        panelEmpleadosBugatti.add(titulo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        titulo11.setBackground(new java.awt.Color(0, 0, 0));
        titulo11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo11.setForeground(new java.awt.Color(0, 0, 0));
        titulo11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo11.setText("Creadores de Carrocerías:");
        panelEmpleadosBugatti.add(titulo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, -1));

        titulo12.setBackground(new java.awt.Color(0, 0, 0));
        titulo12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo12.setForeground(new java.awt.Color(0, 0, 0));
        titulo12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo12.setText("Creadores de Motores:");
        panelEmpleadosBugatti.add(titulo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        titulo13.setBackground(new java.awt.Color(0, 0, 0));
        titulo13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo13.setForeground(new java.awt.Color(0, 0, 0));
        titulo13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo13.setText("Creadores de Ruedas:");
        panelEmpleadosBugatti.add(titulo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, -1));

        titulo14.setBackground(new java.awt.Color(0, 0, 0));
        titulo14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo14.setForeground(new java.awt.Color(0, 0, 0));
        titulo14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo14.setText("Creadores de Accesorios:");
        panelEmpleadosBugatti.add(titulo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, -1));

        titulo15.setBackground(new java.awt.Color(0, 0, 0));
        titulo15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo15.setForeground(new java.awt.Color(0, 0, 0));
        titulo15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo15.setText("Ensambladores:");
        panelEmpleadosBugatti.add(titulo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("jTextField1");
        panelEmpleadosBugatti.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 50, 20));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("jTextField1");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 50, 20));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("jTextField1");
        panelEmpleadosBugatti.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 50, 20));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("jTextField1");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 50, 20));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("jTextField1");
        panelEmpleadosBugatti.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 50, 20));

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("jTextField1");
        panelEmpleadosBugatti.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 50, 20));

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("jTextField1");
        panelEmpleadosBugatti.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 50, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 20, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 20, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 20, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 20, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 20, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("+");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 20, -1));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("+");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 20, -1));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("+");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 20, -1));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("-");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 20, -1));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("-");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 20, -1));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("-");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 20, -1));

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 20, -1));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 20, -1));

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 0, 0));
        jButton15.setText("-");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        panelEmpleadosBugatti.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 20, -1));

        panelBugatti.add(panelEmpleadosBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 270));

        panelAlmacenBugatti.setBackground(new java.awt.Color(0, 255, 153));
        panelAlmacenBugatti.setForeground(new java.awt.Color(0, 0, 0));
        panelAlmacenBugatti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo22.setBackground(new java.awt.Color(0, 0, 0));
        titulo22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        titulo22.setForeground(new java.awt.Color(0, 0, 0));
        titulo22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo22.setText("Almacen");
        panelAlmacenBugatti.add(titulo22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 20));

        jPanel10.setBackground(new java.awt.Color(0, 255, 153));
        jPanel10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo23.setBackground(new java.awt.Color(0, 0, 0));
        titulo23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        titulo23.setForeground(new java.awt.Color(0, 0, 0));
        titulo23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo23.setText("Estadisticas");
        jPanel10.add(titulo23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, -1));

        panelAlmacenBugatti.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 230, 140));

        titulo24.setBackground(new java.awt.Color(0, 0, 0));
        titulo24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo24.setForeground(new java.awt.Color(0, 0, 0));
        titulo24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo24.setText("Vehiculos Especiales:");
        panelAlmacenBugatti.add(titulo24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        titulo25.setBackground(new java.awt.Color(0, 0, 0));
        titulo25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo25.setForeground(new java.awt.Color(0, 0, 0));
        titulo25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo25.setText("Chasis:");
        panelAlmacenBugatti.add(titulo25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, -1));

        titulo26.setBackground(new java.awt.Color(0, 0, 0));
        titulo26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo26.setForeground(new java.awt.Color(0, 0, 0));
        titulo26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo26.setText("Carrocerías:");
        panelAlmacenBugatti.add(titulo26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, -1));

        titulo27.setBackground(new java.awt.Color(0, 0, 0));
        titulo27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo27.setForeground(new java.awt.Color(0, 0, 0));
        titulo27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo27.setText("Motores:");
        panelAlmacenBugatti.add(titulo27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));

        titulo28.setBackground(new java.awt.Color(0, 0, 0));
        titulo28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo28.setForeground(new java.awt.Color(0, 0, 0));
        titulo28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo28.setText("Ruedas:");
        panelAlmacenBugatti.add(titulo28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        titulo29.setBackground(new java.awt.Color(0, 0, 0));
        titulo29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo29.setForeground(new java.awt.Color(0, 0, 0));
        titulo29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo29.setText("Accesorios:");
        panelAlmacenBugatti.add(titulo29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, -1));

        titulo30.setBackground(new java.awt.Color(0, 0, 0));
        titulo30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo30.setForeground(new java.awt.Color(0, 0, 0));
        titulo30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo30.setText("Vehiculos Estandar:");
        panelAlmacenBugatti.add(titulo30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, -1));

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("jTextField1");
        panelAlmacenBugatti.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 50, 20));

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("jTextField1");
        panelAlmacenBugatti.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 50, 20));

        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("jTextField1");
        panelAlmacenBugatti.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 50, 20));

        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setText("jTextField1");
        panelAlmacenBugatti.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 50, 20));

        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("jTextField1");
        panelAlmacenBugatti.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 50, 20));

        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setText("jTextField1");
        panelAlmacenBugatti.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 50, 20));

        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("jTextField1");
        panelAlmacenBugatti.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 50, 20));

        panelBugatti.add(panelAlmacenBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 260, 270));

        panelPantalla.add(panelBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 690, 620));

        panelLamborguini.setBackground(new java.awt.Color(255, 153, 153));
        panelLamborguini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTituloLamborguini.setBackground(new java.awt.Color(255, 102, 102));
        panelTituloLamborguini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo6.setBackground(new java.awt.Color(0, 0, 0));
        titulo6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        titulo6.setForeground(new java.awt.Color(0, 0, 0));
        titulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo6.setText("Lamborguini");
        titulo6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTituloLamborguini.add(titulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 710, 40));

        panelLamborguini.add(panelTituloLamborguini, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 690, 40));

        panelPantalla.add(panelLamborguini, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 683, 620));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Iniciar Simulación");
        panelPantalla.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 700, 370, 30));

        titulo2.setBackground(new java.awt.Color(0, 0, 0));
        titulo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(0, 0, 0));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("Simulación Automotriz");
        panelPantalla.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1366, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panelAlmacenBugatti;
    private javax.swing.JPanel panelBugatti;
    private javax.swing.JPanel panelEmpleadosBugatti;
    private javax.swing.JPanel panelLamborguini;
    private javax.swing.JPanel panelPantalla;
    private javax.swing.JPanel panelTituloBugatti;
    private javax.swing.JPanel panelTituloLamborguini;
    private javax.swing.JLabel titulo10;
    private javax.swing.JLabel titulo11;
    private javax.swing.JLabel titulo12;
    private javax.swing.JLabel titulo13;
    private javax.swing.JLabel titulo14;
    private javax.swing.JLabel titulo15;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo22;
    private javax.swing.JLabel titulo23;
    private javax.swing.JLabel titulo24;
    private javax.swing.JLabel titulo25;
    private javax.swing.JLabel titulo26;
    private javax.swing.JLabel titulo27;
    private javax.swing.JLabel titulo28;
    private javax.swing.JLabel titulo29;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo30;
    private javax.swing.JLabel titulo4;
    private javax.swing.JLabel titulo5;
    private javax.swing.JLabel titulo6;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
